spring.application.name=clone
spring.profiles.include=local

# MongoDB Atlas Configuration (Cloud)
spring.data.mongodb.uri=mongodb+srv://sdmohapatra7_db_user:VkaWRummno1hbPDq@cluster0.axna5dr.mongodb.net/whatsapp_clone?retryWrites=true&w=majority&appName=Cluster0&tls=true
# spring.data.mongodb.database=whatsapp_clone (Already defined in URI)

# Server Port
server.port=8082

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Email Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.expiration-ms=86400000

