spring.application.name=clone

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://sdmohapatra7_db_user:VkaWRummno1hbPDq@cluster0.axna5dr.mongodb.net/whatsapp_clone?retryWrites=true&w=majority&appName=Cluster0&tls=true
spring.mongodb.uri=mongodb+srv://sdmohapatra7_db_user:VkaWRummno1hbPDq@cluster0.axna5dr.mongodb.net/whatsapp_clone?retryWrites=true&w=majority&appName=Cluster0&tls=true
# spring.data.mongodb.uri=mongodb://localhost:27017/whatsapp_clone
spring.data.mongodb.database=whatsapp_clone
spring.mongodb.database=whatsapp_clone

# Server Port
server.port=8082
